using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TheatreAvenue.Models.Interfaces;

//The Location class maps to the "Locations" table in the database and
//implements the ILocation and IEntityBase interfaces
namespace TheatreAvenue.Models.DatabaseModels
{
    [Table("Locations")]
    public class Location : ILocation, IEntityBase
    {
        //The Id property represents the primary key of the "Locations" table
        //and is automatically generated by the database.
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }


        //the data required to be set by the user
        [Required(ErrorMessage = "Country is required")]
        public string Country { get; set; }

        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }
    }
}
