using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TheatreAvenue.Models.Interfaces;

namespace TheatreAvenue.Models.DatabaseModels
{
    // Table attribute specifies the table name to be used in the database
    [Table("Seats")]
    public class Seat : ISeat, IEntityBase
    {
        // DatabaseGenerated attribute specifies that the Id property is automatically generated by the database
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // Required attribute specifies that the Number property is required and cannot be null or empty
        [Required(ErrorMessage = "Number is required")]
        public int Number { get; set; }

        // Required attribute specifies that the Row property is required and cannot be null or empty
        [Required(ErrorMessage = "Row is required")]
        public int Row { get; set; }

        // Required attribute specifies that the Booked property is required and cannot be null or empty
        [Required(ErrorMessage = "Booked is required")]
        public bool Booked { get; set; }

        // UserId property is nullable because a seat may not be booked by anyone
        public int? UserId { get; set; }

        // User property is nullable because a seat may not be booked by anyone
        public User? User { get; set; }
    }
}
